name: Our labs pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/**

jobs:
  build-html:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          architecture: x64

      - name: Run Python script and replace output in HTML
        run: |
          chmod +x .github/generate-html.sh
          .github/generate-html.sh
        env:
          LAB2_EPSILON: ${{ vars.LAB2_EPSILON }}
          LAB2_B_RIGHT: ${{ vars.LAB2_B_RIGHT }}
          LAB3_NUM_TARGETS: ${{ vars.LAB3_NUM_TARGETS }}
          LAB3_NUM_MEASUREMENTS_PER_TARGET: ${{ vars.LAB3_NUM_MEASUREMENTS_PER_TARGET }}
          LAB3_NUM_TRACKED_PARAMS: ${{ vars.LAB3_NUM_TRACKED_PARAMS }}
          LAB3_NUM_COMPUTED_PARAMS_PER_TARGET: ${{ vars.LAB3_NUM_COMPUTED_PARAMS_PER_TARGET }}
          LAB3_L: ${{ vars.LAB3_L }}
          LAB3_M: ${{ vars.LAB3_M }}
          LAB3_V: ${{ vars.LAB3_V }}
          LAB3_VOL: ${{ vars.LAB3_VOL }}
          LAB3_B: ${{ vars.LAB3_B }}
          LAB3_V_NEXT: ${{ vars.LAB3_V_NEXT }}
          LAB3_R0: ${{ vars.LAB3_R0 }}
          LAB5_NUM_REFUSE_Q: ${{ vars.LAB5_NUM_REFUSE_Q }}
          LAB5_NUM_EXP_N: ${{ vars.LAB5_NUM_EXP_N }}
          LAB5_AVG_TIME_RECOV_TB: ${{ vars.LAB5_AVG_TIME_RECOV_TB }}
          LAB5_CUR_TIME_RECOV_TB_DOP: ${{ vars.LAB5_CUR_TIME_RECOV_TB_DOP }}
          LAB5_ACTUAL_DURATION_TPI: ${{ vars.LAB5_ACTUAL_DURATION_TPI }}
          LAB5_VALID_TIME_TPI_DOP: ${{ vars.LAB5_VALID_TIME_TPI_DOP }}
          LAB5_BASIC_PRINC_REL: ${{ vars.LAB5_BASIC_PRINC_REL }}

      - name: Run SpotBugs Analysis
        working-directory: lab4/lab
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
        run: |
          ant spotbugs
          mv ./build/spotbugs-report.html ../../.github/out/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ".github/out/"

      - name: Deploy to pages
        id: deployment
        uses: actions/deploy-pages@v2
